# This file was generated by GoReleaser. DO NOT EDIT.
cask "another" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "another"],
        chdir:          ".",
        writable_paths: ["another"],
        must_succeed:   false
  end

  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "5e3b6a1064d1f646ad900d175dfdaacf82de7344750913950133649e345698a9"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "75784481b39aa132c004f00e2dac30bc05e84c3aca6a09b5a39d0f6d2ca1d0c3"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77f5ad3eebfa6bd0307d98a9006d8fd3ae0681fa058a9831d1eec846a7fa442a"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "78ba43b14a6ebc1da4bbe6b657a8adede5ddde561c692b52c7f4a44c8fe1996b"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_amd64.tar.gz"
    end
  end

  name "another"
  desc "Browse and manage coding-agent sessions, or move one into another agent"
  homepage "https://github.com/nxxxsooo/another"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "another"

  zap trash: [
      "~/.cache/another",
      "~/.config/another",
    ]

end
