# This file was generated by GoReleaser. DO NOT EDIT.
cask "another" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "another"],
        chdir:          ".",
        writable_paths: ["another"],
        must_succeed:   false
  end

  version "0.15.4"

  on_macos do
    on_arm do
      sha256 "50573ef7211e20e40bf19ea9ddfabe8d81af8f8996d00569ff9e3e81cb371c40"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a0ec1d9df7ce7dad64a3984c91f9c1000abb8007e18b753965f68333f753372"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e970dc9a4c74baf17c8edc52670f5b94503401cc70c9429dfb58812f0e5af905"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8503c83054cea94b0c0b8973dcde91b52ceac9c95d92d1ce99cf7e8cbef84bb9"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_amd64.tar.gz"
    end
  end

  name "another"
  desc "Browse and manage coding-agent sessions, or move one into another agent"
  homepage "https://github.com/nxxxsooo/another"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "another"

  zap trash: [
      "~/.cache/another",
      "~/.config/another",
    ]

  caveats <<~EOS
    On its first interactive launch, another adds the shell alias a if that
    name is free. Open a new shell afterwards, or run another aliases install.
  EOS
end
