# This file was generated by GoReleaser. DO NOT EDIT.
cask "another" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "another"],
        chdir:          ".",
        writable_paths: ["another"],
        must_succeed:   false
  end

  version "0.18.0"

  on_macos do
    on_arm do
      sha256 "0912149e64754a8eff8c7743ea4251954a2ee764d9ea707cbf2c9961784b9ecd"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "80a6721f900e00b6418495f380476c928c209cd285325170683d8dd35ad3e4fe"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a838cec89336f71cafb0f6dd54bb2d616f963fa90a80601d680255180d6fae9f"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ad8fe7b9fec3c770aed73cea679d49281a027ab9d57eaa32207873a0ab4fe42"
      url "https://github.com/nxxxsooo/another/releases/download/v#{version}/another_#{version}_linux_amd64.tar.gz"
    end
  end

  name "another"
  desc "Browse and manage coding-agent sessions, or move one into another agent"
  homepage "https://github.com/nxxxsooo/another"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "another"

  zap trash: [
      "~/.cache/another",
      "~/.config/another",
    ]

  caveats <<~EOS
    On its first interactive launch, another adds the shell alias a if that
    name is free. Open a new shell afterwards, or run another aliases install.
  EOS
end
